### ISSUE TITLE
Can not find game.

### ISSUE THREAD

**Issue by creeperlwd** [BernardoGiordano/EventAssistant#23] opened 2016-10-28 12:36 UTC
it doesn't open, doesn't find my pokemon y cart
also doesn't find my installed Pokemon X/Y and ORAS
(3.0 beta)

**Comment by BernardoGiordano** [comment] 2016-10-28 13:08
Can you be more detailed? Are you entering from HBL or cfw? Are you entering fron bank or not? I can't reproduce this error by myself, it works flawlessly for me.

**Comment by creeperlwd** [comment] 2016-10-28 15:15
N3DS 11.2E Luma3DS CIA version of the app

**Comment by BernardoGiordano** [comment] 2016-10-28 15:32
What are you clicking to select the game?

**Comment by creeperlwd** [comment] 2016-10-28 15:35
nothing... it never gives me the option to select a game

**Comment by creeperlwd** [comment] 2016-10-28 15:37
i figured out the problem, if i press yes on check for updates. it doens't find my game. but if i press b it goes to the game select menu

**Comment by BernardoGiordano** [comment] 2016-10-28 16:15
There's a 'CONTINUE' for that purpose, in fact. Closing as this isn't an issue.

**Closed by BernardoGiordano** 2016-10-28 16:15 UTC
